apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox  # Specify the namespace
spec:
  type: ClusterIP  # Service type
  ports:
    - port: 4111         # Port that the service will expose
      targetPort: 3111   # Port on the container to forward traffic to
      protocol: TCP      # Protocol used
  selector:
    app: techtrends  # This should match the labels in your deployment
